package at.co.svc.agate.openapi.phase2.model;


public enum AgateTestCaseType {

    BASELINE_VALID,
    FULL_REQUEST,

    OPTIONAL_PARAMETER,

    MISSING_REQUIRED_PARAMETER,
    MISSING_REQUIRED_BODY_PROPERTY,


    ENUM_VALUE,
    INVALID_ENUM,

    BODY_ENUM_VALUE,
    BODY_INVALID_ENUM,


    MINIMUM,
    MAXIMUM,
    BELOW_MINIMUM,
    ABOVE_MAXIMUM,

    EXCLUSIVE_MINIMUM_VALID,
    EXCLUSIVE_MINIMUM_INVALID,

    EXCLUSIVE_MAXIMUM_VALID,
    EXCLUSIVE_MAXIMUM_INVALID,

    MULTIPLE_OF_VALID,
    MULTIPLE_OF_INVALID,


    BODY_MINIMUM,
    BODY_MAXIMUM,
    BODY_BELOW_MINIMUM,
    BODY_ABOVE_MAXIMUM,

    BODY_EXCLUSIVE_MINIMUM_VALID,
    BODY_EXCLUSIVE_MINIMUM_INVALID,

    BODY_EXCLUSIVE_MAXIMUM_VALID,
    BODY_EXCLUSIVE_MAXIMUM_INVALID,

    BODY_MULTIPLE_OF_VALID,
    BODY_MULTIPLE_OF_INVALID,


    MIN_LENGTH,
    MAX_LENGTH,
    BELOW_MIN_LENGTH,
    ABOVE_MAX_LENGTH,

    PATTERN_VALID,
    PATTERN_INVALID,

    FORMAT_VALID,
    FORMAT_INVALID,


    BODY_MIN_LENGTH,
    BODY_MAX_LENGTH,
    BODY_BELOW_MIN_LENGTH,
    BODY_ABOVE_MAX_LENGTH,

    BODY_PATTERN_VALID,
    BODY_PATTERN_INVALID,

    BODY_FORMAT_VALID,
    BODY_FORMAT_INVALID,


    MIN_ITEMS,
    MAX_ITEMS,
    BELOW_MIN_ITEMS,
    ABOVE_MAX_ITEMS,

    UNIQUE_ITEMS_VALID,
    UNIQUE_ITEMS_INVALID,


    ARRAY_ITEM_MIN_LENGTH,
    ARRAY_ITEM_MAX_LENGTH,
    ARRAY_ITEM_BELOW_MIN_LENGTH,
    ARRAY_ITEM_ABOVE_MAX_LENGTH,

    ARRAY_ITEM_PATTERN_VALID,
    ARRAY_ITEM_PATTERN_INVALID,

    ARRAY_ITEM_FORMAT_VALID,
    ARRAY_ITEM_FORMAT_INVALID,


    BODY_MIN_ITEMS,
    BODY_MAX_ITEMS,
    BODY_BELOW_MIN_ITEMS,
    BODY_ABOVE_MAX_ITEMS,

    BODY_UNIQUE_ITEMS_VALID,
    BODY_UNIQUE_ITEMS_INVALID
}