quarkus.package.type=uber-jar

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=content-disposition
quarkus.http.cors.access-control-max-age=24H


quarkus.http.cors.headers=*


# 1 Quarkus log level (iz unutar aplikacije / CDI)
quarkus.log.level=OFF
quarkus.log.category."at.co.svc.test".level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# Isključi dosadne provere konfiguracije
quarkus.log.category."io.quarkus.config".level=ERROR

# 2
quarkus.banner.enabled=false

# 3 Utisaj Quarkus specifične kategorije koje te nerviraju (na WARN ili ERROR)
quarkus.log.category."io.quarkus".level=WARN
quarkus.log.category."io.qu.config".level=OFF
quarkus.log.category."io.netty".level=WARN
quarkus.log.category."org.jboss.threads".level=WARN