openapi: 3.0.3

info:
  title: AGATE Common Schemas
  version: 1.0.0

paths: {}

components:

  schemas:

    Address:
      type: object
      required:
        - street
        - city
        - country
      properties:

        street:
          type: string
          minLength: 1
          maxLength: 100

        city:
          type: string
          minLength: 1
          maxLength: 100

        postalCode:
          type: string
          pattern: '^[0-9]{4,10}$'

        country:
          type: string
          enum:
            - AT
            - DE
            - CH
            - BA


    Contact:
      type: object
      properties:

        email:
          type: string
          format: email

        phone:
          type: string

        address:
          $ref: '#/components/schemas/Address'


    Company:
      type: object
      required:
        - id
        - name
      properties:

        id:
          type: integer
          format: int64

        name:
          type: string

        address:
          $ref: '#/components/schemas/Address'

        contact:
          $ref: '#/components/schemas/Contact'