openapi: 3.0.3

info:
  title: AGATE Pet Module Test
  version: 1.0.0

paths:

  /pet:

    post:

      operationId: addPet

      requestBody:
        required: true

        content:

          application/json:

            schema:
              $ref: '#/components/schemas/Pet'

      responses:

        '200':
          description: Successful operation

          content:

            application/json:

              schema:
                $ref: '#/components/schemas/Pet'

        '400':
          description: Invalid input


components:

  schemas:

    Category:

      type: object

      properties:

        id:
          type: integer
          format: int64
          example: 1

        name:
          type: string
          example: Dogs


    Tag:

      type: object

      properties:

        id:
          type: integer
          format: int64
          example: 1

        name:
          type: string
          example: example


    Pet:

      type: object

      required:
        - name
        - photoUrls

      properties:

        id:
          type: integer
          format: int64
          example: 10

        name:
          type: string
          example: doggie

        category:
          $ref: '#/components/schemas/Category'

        photoUrls:
          type: array

          items:
            type: string

        tags:
          type: array

          items:
            $ref: '#/components/schemas/Tag'

        status:
          type: string
          enum:
            - available
            - pending
            - sold