openapi: 3.0.3

info:
  title: AGATE Phase 0 External Ref Test API
  version: 1.0.0

paths:

  /companies/{id}:

    get:
      operationId: getCompany

      parameters:

        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

      responses:

        '200':
          description: Company found
          content:
            application/json:
              schema:
                $ref: './common-v1.yaml#/components/schemas/Company'

        '404':
          description: Company not found


  /companies:

    post:
      operationId: createCompany

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object

              required:
                - name
                - address

              properties:

                name:
                  type: string
                  minLength: 2
                  maxLength: 100

                address:
                  $ref: './common-v1.yaml#/components/schemas/Address'

                contact:
                  $ref: './common-v1.yaml#/components/schemas/Contact'

      responses:

        '201':
          description: Company created
          content:
            application/json:
              schema:
                $ref: './common-v1.yaml#/components/schemas/Company'