openapi: 3.0.3

info:
  title: AGATE Phase 0 PathItem Ref Test
  version: 1.0.0

paths:

  /alive:
    $ref: './common-paths-v1.yaml#/paths/~1alive'

  /v1/alive:
    $ref: './common-paths-v1.yaml#/paths/~1alive'

  /users:

    get:
      operationId: getUsers

      responses:

        '200':
          description: Users returned
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string