# --- USER: DEMOS ---
DEMOS.Mustermann.serverip=10.134.242.129
DEMOS.Mustermann.email=muste.mustermann@gmail.com
DEMOS.Tester1.serverip=10.134.242.129
DEMOS.Tester1.email=muste.mustermann@gmail.com

# --- USER: ACME ---
ACME.Testuser.name=Mustermann


