# Service Port
quarkus.http.port=8088

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=*
quarkus.http.cors.exposed-headers=*

# Isklju\u010Divanje problemati\u010Dnog build-stepa
quarkus.langchain4j.chat-memory.enabled=false
# LangChain4j Ollama konfiguracija
quarkus.langchain4j.ollama.base-url=http://localhost:11434
#quarkus.langchain4j.ollama.chat-model.model-id=llama3
quarkus.langchain4j.ollama.chat-model.model-id=phi3
quarkus.langchain4j.ollama.chat-model.timeout=60s

#quarkus.http.cors=false
#quarkus.http.cors.origins=http://localhost:4200
#quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
#quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
#quarkus.http.cors.exposed-headers=content-disposition
#quarkus.http.cors.access-control-max-age=24H
#
#quarkus.http.cors.headers=*
#quarkus.http.cors.exposed-headers=*


//quarkus.http.cors.headers=*


# 1 Quarkus log level (iz unutar aplikacije / CDI)
quarkus.log.level=OFF
quarkus.log.category."at.co.svc".level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# Isključi dosadne provere konfiguracije
quarkus.log.category."io.quarkus.config".level=ERROR

# 2
quarkus.banner.enabled=false

# 3 Utisaj Quarkus specifične kategorije koje te nerviraju (na WARN ili ERROR)
quarkus.log.category."io.quarkus".level=WARN
quarkus.log.category."io.qu.config".level=OFF
quarkus.log.category."io.netty".level=WARN
quarkus.log.category."org.jboss.threads".level=WARN